version: '3'
services:
  v_central_server:
    container_name: v_central_server
    image: hfl_env-central_server
    volumes:
      - ./server/imputation:/ServerApp/imputation
      - ./server/logs:/ServerApp/logs
      - ./server/launch.sh:/ServerApp/launch.sh
      - ./server/results:/ServerApp/results
      - ./server/target_data:/ServerApp/target_data
      - ./certificates/central_server:/ServerApp/certs
      - ./auth_keys/central_server:/ServerApp/auth_keys
    networks: 
      - VFLnetwork
    stdin_open: true
    tty: true
    expose:
      - 5000
    environment:
      - IMPUTATION_STRATEGY=statistical
# [ statistical - machine_learning - deep_learning ]

  v_node1:
    container_name: v_node1
    image: hfl_env-node
    depends_on:
      - v_central_server
    volumes:
      - ./data/node1_patients:/NodeApp/data 
      - ./nodes/imputation:/NodeApp/imputation
      - ./nodes/logs:/NodeApp/logs
      - ./nodes/results:/NodeApp/results
      - ./nodes/launch.sh:/NodeApp/launch.sh
      - ./certificates/node1:/NodeApp/certs
      - ./auth_keys/node1:/NodeApp/auth_keys
    environment:
      - NODE_ID=1
      - SERVER_ADDRESS=v_central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - VFLnetwork  
    stdin_open: true
    tty: true

  v_node2:
    container_name: v_node2
    image: hfl_env-node
    depends_on:
      - v_central_server
    volumes:
      - ./data/node2_admissions:/NodeApp/data 
      - ./nodes/imputation:/NodeApp/imputation
      - ./nodes/logs:/NodeApp/logs
      - ./nodes/results:/NodeApp/results
      - ./nodes/launch.sh:/NodeApp/launch.sh
      - ./certificates/node2:/NodeApp/certs
      - ./auth_keys/node2:/NodeApp/auth_keys
    environment:
      - NODE_ID=2
      - SERVER_ADDRESS=v_central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - VFLnetwork  
    stdin_open: true
    tty: true

  v_node3:
    container_name: v_node3
    image: hfl_env-node
    depends_on:
      - v_central_server
    volumes:
      - ./data/node3_chartevents:/NodeApp/data 
      - ./nodes/imputation:/NodeApp/imputation
      - ./nodes/logs:/NodeApp/logs
      - ./nodes/results:/NodeApp/results
      - ./nodes/launch.sh:/NodeApp/launch.sh
      - ./certificates/node3:/NodeApp/certs
      - ./auth_keys/node3:/NodeApp/auth_keys
    environment:
      - NODE_ID=3
      - SERVER_ADDRESS=v_central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - VFLnetwork  
    stdin_open: true
    tty: true

  v_node4:
    container_name: v_node4
    image: hfl_env-node
    depends_on:
      - v_central_server
    volumes:
      - ./data/node4_labevents:/NodeApp/data 
      - ./nodes/imputation:/NodeApp/imputation
      - ./nodes/logs:/NodeApp/logs
      - ./nodes/results:/NodeApp/results
      - ./nodes/launch.sh:/NodeApp/launch.sh
      - ./certificates/node4:/NodeApp/certs
      - ./auth_keys/node4:/NodeApp/auth_keys
    environment:
      - NODE_ID=4
      - SERVER_ADDRESS=v_central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - VFLnetwork  
    stdin_open: true
    tty: true

  v_node5:
    container_name: v_node5
    image: hfl_env-node
    depends_on:
      - v_central_server
    volumes: 
      - ./data/node5_icustays:/NodeApp/data 
      - ./nodes/imputation:/NodeApp/imputation
      - ./nodes/logs:/NodeApp/logs
      - ./nodes/results:/NodeApp/results
      - ./nodes/launch.sh:/NodeApp/launch.sh
      - ./certificates/node5:/NodeApp/certs
      - ./auth_keys/node5:/NodeApp/auth_keys
    environment:
      - NODE_ID=5
      - SERVER_ADDRESS=v_central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - VFLnetwork  
    stdin_open: true
    tty: true

networks:
  VFLnetwork:
    driver: bridge
