version: '3'
services:
  central_server:
    container_name: central_server
    image: hfl_env-central_server
    volumes:
      - ./server:/ServerApp
      - ./certificates/central_server:/ServerApp/certs
    networks:
      - FLnetwork
    stdin_open: true
    tty: true
    expose:
      - 5000
    environment:
      - IMPUTATION_STRATEGY=statistical
# [ statistical - machine_learning - deep_learning ]

  node1:
    container_name: node1
    image: hfl_env-node
    depends_on:
      - central_server
    volumes:
      - ./nodes:/NodeApp   
      - ./data/node1:/NodeApp/data 
      - ./certificates/node1:/NodeApp/certs
    environment:
      - NODE_ID=1
      - SERVER_ADDRESS=central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - FLnetwork  
    stdin_open: true
    tty: true

  node2:
    container_name: node2
    image: hfl_env-node
    depends_on:
      - central_server
    volumes:
      - ./nodes:/NodeApp    
      - ./data/node2:/NodeApp/data 
      - ./certificates/node2:/NodeApp/certs
    environment:
      - NODE_ID=2
      - SERVER_ADDRESS=central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - FLnetwork  
    stdin_open: true
    tty: true

  node3:
    container_name: node3
    image: hfl_env-node
    depends_on:
      - central_server
    volumes:
      - ./nodes:/NodeApp    
      - ./data/node3:/NodeApp/data 
      - ./certificates/node3:/NodeApp/certs
    environment:
      - NODE_ID=3
      - SERVER_ADDRESS=central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - FLnetwork  
    stdin_open: true
    tty: true

  node4:
    container_name: node4
    image: hfl_env-node
    depends_on:
      - central_server
    volumes:
      - ./nodes:/NodeApp    
      - ./data/node4:/NodeApp/data 
      - ./certificates/node4:/NodeApp/certs
    environment:
      - NODE_ID=4
      - SERVER_ADDRESS=central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - FLnetwork  
    stdin_open: true
    tty: true

  node5:
    container_name: node5
    image: hfl_env-node
    depends_on:
      - central_server
    volumes:
      - ./nodes:/NodeApp    
      - ./data/node5:/NodeApp/data 
      - ./certificates/node5:/NodeApp/certs
    environment:
      - NODE_ID=5
      - SERVER_ADDRESS=central_server:5000
      - IMPUTATION_STRATEGY=statistical
    networks:
      - FLnetwork  
    stdin_open: true
    tty: true

networks:
  FLnetwork:
    driver: bridge
